package com.example.project02_group09_mohammed_diksha_fidel.data;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// This annotation defines the class as a table named 'activitylog'
@Entity(tableName = "activitylog")
public class ActivityLog {

    // Primary Key (Auto-generated by Room)
    @PrimaryKey(autoGenerate = true)
    public int id;

    @ColumnInfo(name = "userId")
    public int userId; // Foreign key linking to the User table

    @ColumnInfo(name = "type")
    public String type; // e.g., "Steps", "Water", "Sleep"

    @ColumnInfo(name = "value")
    public float value; // e.g., 5000 steps, 8 glasses of water

    @ColumnInfo(name = "timestamp")
    public long timestamp; // When the log was recorded (System.currentTimeMillis())

    // Constructor required by Room
    public ActivityLog(int id, int userId, String type, float value, long timestamp) {
        this.id = id;
        this.userId = userId;
        this.type = type;
        this.value = value;
        this.timestamp = timestamp;
    }

    // You may also need getters if they are used elsewhere, but the constructor is the key.
    public int getId() { return id; }
    public int getUserId() { return userId; }
    public String getType() { return type; }
    public float getValue() { return value; }
    public long getTimestamp() { return timestamp; }
}